site_name: Swebeer

repo_name: swebeer/wiki
#repo_url: https://github.com/daggr8/swebeer
theme:
  name: material
  favicon: resources/favicon.ico
  #logo: resources/swebeer_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - code.annotation
    - navigation.tracking
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: darkblue
      accent_: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: darkblue
      accent_: lime
    
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true